docker:
  bip: '172.17.0.1'
  range: '172.17.0.0/24'
  sorange: '172.17.1.0/24'
  sobip: '172.17.1.1'
  containers:
    'so-dockerregistry':
      final_octet: 20
      port_bindings:
        - 0.0.0.0:5000:5000
    'so-elastic-fleet':
      final_octet: 21
      port_bindings:
        - 0.0.0.0:8220:8220/tcp
    'so-elasticsearch':
      final_octet: 22
      port_bindings:
        - 0.0.0.0:9200:9200/tcp
        - 0.0.0.0:9300:9300/tcp
    'so-idstools':
      final_octet: 25
    'so-influxdb':
      final_octet: 26
      port_bindings:
        - 0.0.0.0:8086:8086
    'so-kibana':
      final_octet: 27
      port_bindings:
        - 0.0.0.0:5601:5601
    'so-kratos':
      final_octet: 28
      port_bindings:
        - 0.0.0.0:4433:4433
        - 0.0.0.0:4434:4434
    'so-logstash':
      final_octet: 29
      port_bindings:
        - 0.0.0.0:3765:3765
        - 0.0.0.0:5044:5044
        - 0.0.0.0:5055:5055
        - 0.0.0.0:5644:5644
        - 0.0.0.0:6050:6050
        - 0.0.0.0:6051:6051
        - 0.0.0.0:6052:6052
        - 0.0.0.0:6053:6053
        - 0.0.0.0:9600:9600
    'so-mysql':
      final_octet: 30
      port_bindings:
        - 0.0.0.0:3306:3306
    'so-nginx':
      final_octet: 31
      port_bindings:
        - 80:80
        - 443:443
    'so-playbook':
      final_octet: 32
      port_bindings:
        - 0.0.0.0:3000:3000
    'so-redis':
      final_octet: 33
      port_bindings:
        - 0.0.0.0:6379:6379
        - 0.0.0.0:9696:9696
    'so-soc':
      final_octet: 34
      port_bindings:
        - 0.0.0.0:9822:9822
    'so-soctopus':
      final_octet: 35
      port_bindings:
        - 0.0.0.0:7000:7000
    'so-strelka-backend':
      final_octet: 36
    'so-strelka-filestream':
      final_octet: 37
    'so-strelka-frontend':
      final_octet: 38
      port_bindings:
        - 0.0.0.0:57314:57314
    'so-strelka-manager':
      final_octet: 39
    'so-strelka-gatekeeper':
      final_octet: 40
      port_bindings:
        - 0.0.0.0:6381:6379
    'so-strelka-coordinator':
      final_octet: 41
      port_bindings:
        - 0.0.0.0:6380:6379
    'so-elastalert':
      final_octet: 42
    'so-curator':
      final_octet: 43
    'so-elastic-fleet-package-registry':
      final_octet: 44
      port_bindings:
        - 0.0.0.0:8080:8080/tcp
    'so-idh':
      final_octet: 45