docker:
  bip:
    description: Bind IP for the default docker interface.
    helpLink: docker.html
    advanced: True
  range:
    description: Default docker IP range for containers.
    helpLink: docker.html
    advanced: True
  sobip:
    description: Bind IP for the SO docker interface.
    helpLink: docker.html
    advanced: True
  sorange:
    description: IP range for the SO docker containers.
    helpLink: docker.html
    advanced: True
  containers:
    so-curator: &dockerOptions
      final_octet:
        description: Last octet of the container IP address.
        helpLink: docker.html
        readonly: True
        advanced: True
        global: True
      port_bindings:
        description: List of port bindings for the container.
        helpLink: docker.html
        advanced: True
        multiline: True
    so-dockerregistry: *dockerOptions
    so-elastalert: *dockerOptions
    so-elastic-fleet-package-registry: *dockerOptions
    so-elastic-fleet: *dockerOptions
    so-elasticsearch: *dockerOptions
    so-idh: *dockerOptions
    so-idstools: *dockerOptions
    so-influxdb: *dockerOptions
    so-kibana: *dockerOptions
    so-kratos: *dockerOptions
    so-logstash: *dockerOptions
    so-mysql: *dockerOptions
    so-nginx: *dockerOptions
    so-playbook: *dockerOptions
    so-redis: *dockerOptions
    so-soc: *dockerOptions
    so-soctopus: *dockerOptions
    so-strelka-backend: *dockerOptions
    so-strelka-coordinator: *dockerOptions
    so-strelka-filestream: *dockerOptions
    so-strelka-frontend: *dockerOptions
    so-strelka-gatekeeper: *dockerOptions
    so-strelka-manager: *dockerOptions