grafana:
  config:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Viewer
    smtp:
      enabled: false
      host: localhost:25
      user: myuser
      # If the password contains # or ; you have to wrap it with trippel quotes. Ex """#password;"""
      password: mypassword
      cert_file: /etc/grafana/config/files/smtp_cert_file.crt
      key_file: /etc/grafana/config/files/smtp_key_file.key
      skip_verify: false
      from_address: admin@grafana.localhost
      from_name: Grafana
      ehlo_identity: dashboard.example.com
#    auth.ldap:
#      enabled: false
#      config_file: /etc/grafana/config/files/ldap.toml
#      allow_sign_up: true
#    enterprise:
#      license_path: /opt/so/conf/grafana/etc/files/license.jwt